export const courses = [
  { label: "Matemáticas", value: "matematicas" },
  { label: "Ciencias Naturales", value: "ciencias_naturales" },
  { label: "Lengua y Literatura", value: "lengua_y_literatura" },
  { label: "Historia", value: "historia" },
  { label: "Geografía", value: "geografia" },
  { label: "Física", value: "fisica" },
  { label: "Química", value: "quimica" },
  { label: "Biología", value: "biologia" },
  { label: "Educación Física", value: "educacion_fisica" },
  { label: "Inglés", value: "ingles" },
  { label: "Francés", value: "frances" },
  { label: "Alemán", value: "aleman" },
  { label: "Arte", value: "arte" },
  { label: "Música", value: "musica" },
  { label: "Tecnología", value: "tecnologia" },
  { label: "Informática", value: "informatica" },
  { label: "Economía", value: "economia" },
  { label: "Psicología", value: "psicologia" },
  { label: "Filosofía", value: "filosofia" },
  { label: "Religión", value: "religion" },
  { label: "Ética", value: "etica" },
  { label: "Sociología", value: "sociologia" },
  { label: "Antropología", value: "antropologia" },
  { label: "Derecho", value: "derecho" },
  { label: "Negocios", value: "negocios" },
  { label: "Contabilidad", value: "contabilidad" },
  { label: "Mercadotecnia", value: "mercadotecnia" },
  { label: "Educación Cívica", value: "educacion_civica" },
  { label: "Geometría", value: "geometria" },
  { label: "Algebra", value: "algebra" },
  { label: "Otro", value: "otro" },
];
